### ISSUE TITLE
Viewport view disappears after seconds

### ISSUE THREAD

**Issue by cbonillo91** [alfarok/DynamoViewport#13]
Hi! I'm just beginning to work with Dynamo Extensions and I would need to use ChromiumWebBrowser in order to show certain information about the nodes of the system.
Since your project is super complete and uses a structure that it's really similar to what I want to do, I cloned your DynamoViewport by following the instructions.
It worked perfectly, the first time I downloaded it, but after doing some tests (to learn how it worked) I decided to remove the repository and clone it again. I haven't managed to make it work again since then: the grid showes in the view disappears for just a couple of seconds but then disappears, not allowing me to use the extension...
Do you know what the problem could be? Thank you very much!

**Comment by alfarok** [comment]
Hey @cbonillo91, sorry I for the delay.  It sounds like chromium may be crashing.  Can you debug using your regular web browser  on port 8088 while the extension is running and see if there are any errors
```
http://localhost:8088/
```

**Comment by cbonillo91** [comment]
Hey! At the end I managed to make what I wanted to do work after a lot of testing and fighting with the chromium... Thanks for the reply nevertheless! I will do that if I have to come back to your code and it failes again :)
