### ISSUE TITLE
Change the rotation angle

### ISSUE THREAD

**Issue by Montoyez** [alfarok/DynamoViewport#17]
Hi @Alfarok,

Thanks again for all the help in the previous issue. I have been working with the Viewport this week and It is a very useful tool to create quick videos with our geometry in a very clean way. Please have a look to the last video I have done. 

![GIF DNA](https://user-images.githubusercontent.com/23310681/81281591-54a86580-905a-11ea-8d73-5f3b40f37320.gif)

I am wondering if there is an easy way to tweak the code and see the commands bar of the CEF browser to change more parameters. I would love to only rotate around the z axis in some cases.

Have a good day and trust you keep safe.

Regards,
Sergio

**Comment by alfarok** [comment]
Check out this line in the [three.js render loop](https://github.com/alfarok/DynamoViewport/blob/master/src/ViewportViewExtension/ViewportViewExtension/Resources/assests/js/viewer.js#L104).  Each time render is called all objects in the scene are rotated uniformly about the X, Y, and Z axis based on the menu slider value.  This isn't ideal in most scenarios but again this project was intended to serve as an example/playground for seeing what's possible.  You should be able to do just about anything [three.js](https://github.com/mrdoob/three.js/) is capable of so if you are interested in learning more I would check out the project and docs.  It is a very well supported and maintained open source library.
