### ISSUE TITLE
The name "ChromiumWebBrowser" does not exist in the namespace

### ISSUE THREAD

**Issue by DmitryDronovDre** [alfarok/DynamoViewport#30]
Try to download and build
It show me this
<img width="854" alt="image" src="https://user-images.githubusercontent.com/110477920/186401743-25d3a1bb-d604-4643-bee6-97607469d89e.png">

Error	XDG0008	The name "ChromiumWebBrowser" does not exist in the namespace "clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf".	

Chrome are installed

**Comment by DmitryDronovDre** [comment]
I just set x64 and it work
<img width="206" alt="image" src="https://user-images.githubusercontent.com/110477920/186419625-7db6e1e1-0d7f-4459-8aa7-8fe68fa40b80.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/110477920/186419739-0839ac0f-9e66-469f-92cb-30463d66cd4c.png">

**Comment by DmitryDronovDre** [comment]
Run it but it not work for mee
<img width="623" alt="image" src="https://user-images.githubusercontent.com/110477920/186422853-d4e8c84d-4133-4b0f-af80-02b7efb66090.png">

**Comment by alfarok** [comment]
Hey @DmitryDronovDre, I have not run this project in several years.  There could be several possible issues with using newer versions of Dynamo.  If you can provide a little more information I can try to determine what may be happening.

Are you using Dynamo via Revit?

What version of Dynamo/Revit are you running?  

Are you manually copying the package to your packages folder?

Do you see the `Launch Viewport` menu option under the `View` tab on the main Dynamo toolbar?

If you navigate to `http://localhost:8088/` in a web browser while the extension is running do you see any errors in the console?

Cheers!
